### ISSUE TITLE
Jekyll fails locally

### ISSUE THREAD

**Issue by mehdi-benallegue** [jrl-umi3218/jrl-umi3218.github.com#19]
When I try running Jekyll on the root I have the following 

```
jrl-umi3218.github $ jekyll server --safe --trace                                                                                                    1 18:30:52
/home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:302:in `check_for_activated_spec!': You have already activated i18n 1.8.9, but your Gemfile requires i18n 0.9.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:31:in `block in setup'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:152:in `each'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:152:in `each'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:26:in `map'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:26:in `setup'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler.rb:148:in `setup'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/exe/jekyll:11:in `<top (required)>'
        from /home/benallegue/.rbenv/versions/3.0.0/bin/jekyll:23:in `load'
        from /home/benallegue/.rbenv/versions/3.0.0/bin/jekyll:23:in `<main>'
```

And if I follow the advice I have

```
jrl-umi3218.github $ bundle exec jekyll server --safe --trace                                                                                                     1 18:30:59
Configuration file: /media/benallegue/work/Mehdi/AIST/other/websites/jrl-umi3218.github/_config.yml
            Source: /media/benallegue/work/Mehdi/AIST/other/websites/jrl-umi3218.github
       Destination: /media/benallegue/work/Mehdi/AIST/other/websites/jrl-umi3218.github/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 6.903 seconds.
bundler: failed to load command: jekyll (/home/benallegue/.rbenv/versions/3.0.0/bin/jekyll)
/home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:75:in `proc_version'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:40:in `bash_on_windows?'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:77:in `watch'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:43:in `process'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
        from /home/benallegue/.rbenv/versions/3.0.0/bin/jekyll:23:in `load'
        from /home/benallegue/.rbenv/versions/3.0.0/bin/jekyll:23:in `<top (required)>'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        from /home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
        from /home/benallegue/.rbenv/versions/3.0.0/bin/bundle:23:in `load'
        from /home/benallegue/.rbenv/versions/3.0.0/bin/bundle:23:in `<main>'
```

It seems it fails when checking for the version of the OS. 

`/home/benallegue/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:`
 ```
       @proc_version ||= begin
          Pathutil.new(
            "/proc/version"
          ).read
```

It is weird that it fails there (I thought it would be a very tested code) but I have no clue. Sorry

------------------------------------------------------------------------------
Additional information
OS Ubuntu 18.04.
Local installation of Ruby (I tried with apt version and I had many problems. However if it should have worked I can show these problems)
The content of my `/proc/version` 
`Linux version 5.4.0-47-generic (buildd@lgw01-amd64-038) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020`

**Comment by gergondet** [comment]
Hi @mehdi-benallegue 

The missing step for bundle is `bundle install`

**Comment by mehdi-benallegue** [comment]
Thanks, but I did it already (just did it again in case of a miracle and same issues).

**Comment by mehdi-benallegue** [comment]
I fixed it by following the steps at the page https://jekyllrb.com/docs/installation/ubuntu/

I will update the readme accordingly

**Comment by gergondet** [comment]
Hi @mehdi-benallegue 

Good to know, thanks!

In the meantime I've added a simple Dockerfile and instructions to run the build in docker
